config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators do
    collection do
      get 'export_participants'
    end
  end
  resources :registries

  post '/registries/:id/remove_coordinator/:coordinator_id' => 'registries#remove_coordinator', as: :registry_remove_coordinator
  post '/coordinators/:id/remove_registry/:registry_id' => 'coordinators#remove_registry', as: :coordinator_remove_registry

  root 'welcome#index'

end

app/models/coordinator.rb
class Coordinator < ActiveRecord::Base
  require 'csv'

  validates_uniqueness_of :email
  validates_presence_of :email

  has_and_belongs_to_many :registries, -> { distinct }
  has_many :enrollments
  has_many :participants, through: :enrollments

  def self.to_csv
    coordinator_header = %w{Coordinator_Name Email Phone}
    participant_header = %w{Participant_Name Gender DOB}
    coordinator_attributes = %w{name email phone}
    participant_attributes = %w{name gender dob}

    CSV.generate(headers: true) do |csv|
      csv << [coordinator_header, participant_header].flatten

      all.each do |c|
        coordinator_values = coordinator_attributes.map{ |attr| c.send(attr) }
        c.participants.uniq.each do |p|
          participant_values = participant_attributes.map{ |attr| p.send(attr) }
          csv << [coordinator_values, participant_values].flatten
        end
      end
    end
  end
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: [:show, :edit, :update, :destroy, :remove_registry]
  before_action :build_options_for_selects, only: [:new, :edit, :create, :update]

  # GET /coordinators
  # GET /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1
  # GET /coordinators/1.json
  def show
    @registries = @coordinator.registries
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators
  # POST /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1
  # PATCH/PUT /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: 'Coordinator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_registry
    registry = Registry.where(id: params[:registry_id]).first

    respond_to do |format|
      if registry && @coordinator.registries.include?(registry)
        @coordinator.registries.delete(registry)
        format.json { render plain: "OK", status: :ok }
      else
        format.json { render plain: "Error", status: 400 }
      end
    end
  end

  def export_participants
    csv_data = Coordinator.to_csv

    respond_to do |format|
      format.html {render plain: csv_data, status: :ok}
      format.csv { send_data csv_data, filename: "participants-#{Date.today}.csv" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinator_params
      params.require(:coordinator).permit(:email, :name, :phone, registry_ids:[])
    end

    def build_options_for_selects
      @registries = Registry.all
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_form.html.erb
<%= simple_form_for(@coordinator) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :name %>
    <%= f.input :phone %>
    <%= f.association :registries, :collection => @registries.collect{|r| ["#{r.name} <#{r.location}>",r.id]}, :label => "Registries (name <location>)"%>
  </div>

  <div class="form-actions">
    <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing Coordinator</h1>

<%= render 'form' %>

app/views/coordinators/index.html.erb
<%- model_class = Coordinator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:email) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:phone) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @coordinators.each do |coordinator| %>
      <tr>
        <td><%= link_to coordinator.email, coordinator_path(coordinator) %></td>
        <td><%= coordinator.name %></td>
        <td><%= coordinator.phone %></td>
        <td><%= coordinator.created_at.strftime("%B %m, %Y") %></td>
        <td>
          <%= link_to "Show", coordinator_path(coordinator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_coordinator_path(coordinator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      coordinator_path(coordinator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_coordinator_path,
            :class => 'btn btn-primary' %>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= render 'form' %>

app/views/coordinators/show.html.erb
<%- model_class = Coordinator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @coordinator.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @coordinator.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @coordinator.phone %></dd>
</dl>

<div class="show_page_buttons">
    <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
    <%= link_to "All", coordinators_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_coordinator_path(@coordinator), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                coordinator_path(@coordinator),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
</div>





<h2> Associated Registries: </h2>
<% if @registries.blank? %>
    <div> The registry has no coordinators </div>
<% else %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Registry Open</th>
        <th>Created At</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @registries.each do |registry| %>
          <tr>
            <td><%= link_to registry.name, registry_path(registry) %></td>
            <td><%= registry.location %></td>
            <td><%= registry.state %></td>
            <td><%= registry.created_at.strftime("%B %m, %Y") %></td>
            <td><%= link_to "Remove Association", coordinator_remove_registry_path(@coordinator, registry), remote: true, method: :post, class: "remove_associations" %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>