config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators do
    collection do
      get 'export_participants'
    end
  end
  resources :registries

  post '/registries/:id/remove_coordinator/:coordinator_id' => 'registries#remove_coordinator', as: :registry_remove_coordinator
  post '/coordinators/:id/remove_registry/:registry_id' => 'coordinators#remove_registry', as: :coordinator_remove_registry

  root 'welcome#index'

end

app/models/registry.rb
class Registry < ActiveRecord::Base
  validates_uniqueness_of :name, scope: :location, message: "combination of name and location must be unique"
  validates_uniqueness_of :location, scope: :name, message: "combination of name and location must be unique"

  has_and_belongs_to_many :coordinators, -> { distinct }
  has_many :enrollments
  has_many :participants, through: :enrollments

  scope :open, -> {where(state: true)}
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: [:show, :edit, :update, :destroy, :remove_coordinator]
  before_action :build_options_for_selects, only: [:new, :edit, :create, :update]

  # GET /registries
  # GET /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
    @coordinators = @registry.coordinators.includes(:participants)
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_coordinator
    coordinator = Coordinator.where(id: params[:coordinator_id]).first

    respond_to do |format|
      if coordinator && @registry.coordinators.include?(coordinator)
        @registry.coordinators.delete(coordinator)
        format.html { redirect_to @registry, notice: 'Coordinator was successfully removed.' }
        format.json { render plain: "OK", status: :ok }
      else
        format.html { redirect_to @registry, notice: 'Something went wrong !!!' }
        format.json { render plain: "Error", status: 400 }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registry_params
      params.require(:registry).permit(:name, :location, :state, coordinator_ids:[])
    end

    def build_options_for_selects
      @coordinators = Coordinator.all
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= simple_form_for(@registry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :state, :label => "Registry Open" %>
    <%= f.association :coordinators, :collection => @coordinators.collect{|c| ["#{c.name} <#{c.email}>",c.id]}, :label => "Coordinators (name <email>)"%>
  </div>

  <div class="form-actions">
    <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Editing Registry</h1>

<%= render 'form' %>

app/views/registries/index.html.erb
<%- model_class = Registry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:location) %></th>
    <th>Registry Open</th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @registries.each do |registry| %>
      <tr>
        <td><%= link_to registry.name, registry_path(registry) %></td>
        <td><%= registry.location %></td>
        <td><%= registry.state %></td>
        <td><%= registry.created_at.strftime("%B %m, %Y") %></td>
        <td>
          <%= link_to "Show", registry_path(registry), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_registry_path(registry), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      registry_path(registry),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_registry_path,
            :class => 'btn btn-primary' %>

app/views/registries/new.html.erb
<h1>New Registry</h1>

<%= render 'form' %>

app/views/registries/show.html.erb
<%- model_class = Registry -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @registry.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @registry.location %></dd>
  <dt><strong>Registry Open:</strong></dt>
  <dd><%= @registry.state %></dd>
</dl>

<div class="show_page_buttons">
  <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
  <%= link_to "All", registries_path, :class => 'btn btn-default' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_registry_path(@registry), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              registry_path(@registry),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>


<h2> Associated Participants grouped by Coordinators : </h2>
<% if @coordinators.blank? %>
    <div> No coordinators are associated with this registry </div>
<% else %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Created At</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @coordinators.each do |coordinator| %>
          <tr>
            <td><%= link_to coordinator.email, coordinator_path(coordinator) %></td>
            <td><%= coordinator.name %></td>
            <td><%= coordinator.phone %></td>
            <td><%= coordinator.created_at.strftime("%B %m, %Y") %></td>
            <td><%= link_to "Remove Association", registry_remove_coordinator_path(@registry, coordinator), method: :post, class: "remove_associations12" %></td>
          </tr>

          <tr class="associated_tr">
            <td style="padding-left: 50px">Participants:</td>
            <td colspan="4">
              <% coordinator.participants.uniq.each do |participant| %>
                <%= link_to participant.name, participant_path(participant.id) %> <br/>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>