config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators do
    collection do
      get 'export_participants'
    end
  end
  resources :registries

  post '/registries/:id/remove_coordinator/:coordinator_id' => 'registries#remove_coordinator', as: :registry_remove_coordinator
  post '/coordinators/:id/remove_registry/:registry_id' => 'coordinators#remove_registry', as: :coordinator_remove_registry

  root 'welcome#index'

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  validates_uniqueness_of :participant_id, scope: :registry_id, message: "participant can't be enrolled in the same registry more than once"

  belongs_to :registry
  belongs_to :participant
  belongs_to :coordinator

  METHOD_OF_CONTACT = [:phone, :email]
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :build_options_for_selects, only: [:new, :edit, :create, :update]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:method_of_contact, :remarks, :date_of_enrollment, :registry_id, :participant_id, :coordinator_id)
    end

    def build_options_for_selects
      @registries = Registry.open
      @coordinators = Coordinator.all
      @participants = Participant.all
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.association :registry, collection: @registries.collect{|r| ["#{r.name} <#{r.location}>",r.id]},
                      label: "Registry (name <location>)",
                      include_blank: false
    %>
    <%= f.association :participant, include_blank: false %>
    <%= f.association :coordinator, collection: @coordinators.collect{|c| ["#{c.name} <#{c.email}>",c.id]},
                      label: "Coordinator performing enrollment (name <email>)",
                      include_blank: false
    %>
    <%= f.input :method_of_contact, collection: Enrollment::METHOD_OF_CONTACT, include_blank: false %>
    <%= f.input :date_of_enrollment %>
    <%= f.input :remarks %>
  </div>

  <div class="form-actions">
    <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form' %>

app/views/enrollments/index.html.erb
<%- model_class = Enrollment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>Participant</th>
    <th>Registry</th>
    <th>Coordinator</th>
    <th>Method Of Contact</th>
    <th>Date Of Enrollment</th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= link_to enrollment.id, enrollment_path(enrollment) %></td>
        <td><%= enrollment.participant.try(:name) %></td>
        <td><%= enrollment.registry.try(:name) %><<%= enrollment.registry.try(:location) %>></td>
        <td><%= enrollment.coordinator.try(:name) %><<%= enrollment.coordinator.try(:email) %>></td>
        <td><%= enrollment.method_of_contact %></td>
        <td><%= enrollment.date_of_enrollment %></td>
        <td><%= enrollment.created_at.strftime("%B %m, %Y") %></td>
        <td>
          <%= link_to "Show", enrollment_path(enrollment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_enrollment_path(enrollment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      enrollment_path(enrollment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_enrollment_path,
            :class => 'btn btn-primary' %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form' %>

app/views/enrollments/show.html.erb
<%- model_class = Enrollment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Registry:</dt>
  <dd><%= @enrollment.registry.try(:name) %> < <%= @enrollment.registry.try(:location) %> ></dd>
  <dt>Participant:</dt>
  <dd><%= @enrollment.participant.try(:name) %></dd>
  <dt>Coordinator:</dt>
  <dd><%= @enrollment.coordinator.try(:name) %> < <%= @enrollment.coordinator.try(:email) %> ></dd>
  <dt>Method of contact:</dt>
  <dd><%= @enrollment.method_of_contact %></dd>
  <dt>Date Of Enrollment:</dt>
  <dd><%= @enrollment.date_of_enrollment %></dd>
  <dt>Remarks:</dt>
  <dd><%= @enrollment.remarks %></dd>
</dl>

<div class="show_page_buttons">
    <%= link_to "Back", "javascript:history.back()", :class => 'btn btn-default' %>
    <%= link_to "All", enrollments_path, :class => 'btn btn-default' %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_enrollment_path(@enrollment), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                enrollment_path(@enrollment),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
</div>